import { Registry } from "@/registry/schema"

const ui: Registry = [
  {
    name: "button",
    type: "components:ui",
    dependencies: ["@radix-ui/react-slot"],
    files: ["ui/button.tsx"],
  },
  {
    name: "card",
    type: "components:ui",
    files: ["ui/card.tsx"],
  },
  {
    name: "input",
    type: "components:ui",
    files: ["ui/input.tsx"],
  },
  {
    name: "label",
    type: "components:ui",
    files: ["ui/label.tsx"],
  },
  {
    name: "select",
    type: "components:ui",
    dependencies: ["@radix-ui/react-select"],
    files: ["ui/select.tsx"],
  },
  {
    name: "dialog",
    type: "components:ui",
    dependencies: ["@radix-ui/react-dialog"],
    files: ["ui/dialog.tsx"],
  },
  {
    name: "toast",
    type: "components:ui",
    dependencies: ["@radix-ui/react-toast"],
    files: ["ui/toast.tsx", "ui/use-toast.ts", "ui/toaster.tsx"],
  },
  {
    name: "skeleton",
    type: "components:ui",
    files: ["ui/skeleton.tsx"],
  },
  {
    name: "dropdown-menu",
    type: "components:ui",
    files: ["ui/dropdown-menu.tsx"],
  },
]

const buidl: Registry = [
  {
    name: "address",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["toast"],
    files: ["buidl/address.tsx"],
  },
  {
    name: "balance",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/balance.tsx"],
  },
  {
    name: "block-explorer-link",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/block-explorer-link.tsx"],
  },
  {
    name: "block-number",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/block-number.tsx"],
  },
  {
    name: "nonce",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/nonce.tsx"],
  },
  {
    name: "transaction",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/transaction.tsx"],
  },
  {
    name: "transaction-status",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/transaction-status.tsx"],
  },
  {
    name: "fee-data",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/fee-data.tsx"],
  },
  {
    name: "sign-message-button",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["button", "error-message"],
    files: ["buidl/sign-message-button.tsx"],
  },
  {
    name: "blockie",
    type: "components:buidl",
    dependencies: ["wagmi", "ethereum-blockies-base64"],
    registryDependencies: ["skeleton"],
    files: ["buidl/blockie.tsx"],
  },
  {
    name: "ens-avatar",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["blockie", "skeleton"],
    files: ["buidl/ens-avatar.tsx"],
  },
  {
    name: "ens-name",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["address", "skeleton"],
    files: ["buidl/ens-name.tsx"],
  },
  {
    name: "ens-address",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["address", "skeleton", "error-message"],
    files: ["buidl/ens-address.tsx"],
  },
  {
    name: "image-ipfs",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/image-ipfs.tsx"],
  },
  {
    name: "is-wallet-connected",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/is-wallet-connected.tsx"],
  },
  {
    name: "is-wallet-disconnected",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/is-wallet-disconnected.tsx"],
  },
  {
    name: "wallet-connect",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["button", "dialog"],
    files: ["buidl/wallet-connect.tsx"],
  },
  {
    name: "wallet-disconnect",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["button"],
    files: ["buidl/wallet-disconnect.tsx"],
  },
  {
    name: "erc20-balance",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc20/erc20-balance.tsx"],
  },
  {
    name: "erc20-decimals",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc20/erc20-decimals.tsx"],
  },
  {
    name: "erc20-name",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc20/erc20-name.tsx"],
  },
  {
    name: "erc20-select-and-amount",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-select-and-amount.tsx"],
  },
  {
    name: "erc20-select",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-select.tsx"],
  },
  {
    name: "erc20-symbol",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc20/erc20-symbol.tsx"],
  },
  {
    name: "erc20-total-supply",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc20/erc20-total-supply.tsx"],
  },
  {
    name: "erc721-name",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-name.tsx"],
  },
  {
    name: "erc721-symbol",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-symbol.tsx"],
  },
  {
    name: "erc721-owner-of",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-owner-of.tsx"],
  },
  {
    name: "erc721-total-supply",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-total-supply.tsx"],
  },
  {
    name: "erc721-token-uri",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-token-uri.tsx"],
  },
  {
    name: "erc721-metadata",
    type: "components:buidl",
    folder: "erc721",
    dependencies: ["wagmi"],
    registryDependencies: ["skeleton", "error-message"],
    files: ["buidl/erc721/erc721-metadata.tsx"],
  },
  {
    name: "error-message",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/error-message.tsx"],
  },
  {
    name: "network-selection",
    type: "components:buidl",
    dependencies: ["wagmi"],
    registryDependencies: ["dropdown-menu"],
    files: ["buidl/network-selection.tsx"],
  },
]

const example: Registry = [
  {
    name: "nonce-demo",
    type: "components:example",
    registryDependencies: ["nonce"],
    files: ["example/nonce-demo.tsx"],
  },
  {
    name: "address-demo",
    type: "components:example",
    registryDependencies: ["address"],
    files: ["example/address-demo.tsx"],
  },
  {
    name: "balance-demo",
    type: "components:example",
    registryDependencies: ["balance"],
    files: ["example/balance-demo.tsx"],
  },
  {
    name: "block-explorer-link-demo",
    type: "components:example",
    registryDependencies: ["block-explorer-link"],
    files: ["example/block-explorer-link-demo.tsx"],
  },
  {
    name: "block-number-demo",
    type: "components:example",
    registryDependencies: ["block-number"],
    files: ["example/block-number-demo.tsx"],
  },
  {
    name: "transaction-demo",
    type: "components:example",
    registryDependencies: ["transaction"],
    files: ["example/transaction-demo.tsx"],
  },
  {
    name: "transaction-status-demo",
    type: "components:example",
    registryDependencies: ["transaction-status"],
    files: ["example/transaction-status-demo.tsx"],
  },
  {
    name: "sign-message-button-demo",
    type: "components:example",
    registryDependencies: ["sign-message-button"],
    files: ["example/sign-message-button-demo.tsx"],
  },
  {
    name: "fee-data-demo",
    type: "components:example",
    registryDependencies: ["fee-data"],
    files: ["example/fee-data-demo.tsx"],
  },
  {
    name: "blockie-demo",
    type: "components:example",
    registryDependencies: ["blockie"],
    files: ["example/blockie-demo.tsx"],
  },
  {
    name: "ens-avatar-demo",
    type: "components:example",
    registryDependencies: ["ens-avatar"],
    files: ["example/ens-avatar-demo.tsx"],
  },
  {
    name: "ens-name-demo",
    type: "components:example",
    registryDependencies: ["ens-name"],
    files: ["example/ens-name-demo.tsx"],
  },
  {
    name: "ens-address-demo",
    type: "components:example",
    registryDependencies: ["ens-address"],
    files: ["example/ens-address-demo.tsx"],
  },
  {
    name: "image-ipfs-demo",
    type: "components:example",
    registryDependencies: ["image-ipfs"],
    files: ["example/image-ipfs-demo.tsx"],
  },
  {
    name: "is-wallet-connected-demo",
    type: "components:example",
    registryDependencies: ["is-wallet-connected"],
    files: ["example/is-wallet-connected-demo.tsx"],
  },
  {
    name: "is-wallet-disconnected-demo",
    type: "components:example",
    registryDependencies: ["is-wallet-disconnected"],
    files: ["example/is-wallet-disconnected-demo.tsx"],
  },
  {
    name: "wallet-connect-demo",
    type: "components:example",
    registryDependencies: ["wallet-connect"],
    files: ["example/wallet-connect-demo.tsx"],
  },
  {
    name: "wallet-disconnect-demo",
    type: "components:example",
    registryDependencies: ["wallet-disconnect"],
    files: ["example/wallet-disconnect-demo.tsx"],
  },
  {
    name: "erc20-balance-demo",
    type: "components:example",
    registryDependencies: ["erc20-balance"],
    files: ["example/erc20-balance-demo.tsx"],
  },
  {
    name: "erc20-decimals-demo",
    type: "components:example",
    registryDependencies: ["erc20-decimals"],
    files: ["example/erc20-decimals-demo.tsx"],
  },
  {
    name: "erc20-name-demo",
    type: "components:example",
    registryDependencies: ["erc20-name"],
    files: ["example/erc20-name-demo.tsx"],
  },
  {
    name: "erc20-select-and-amount-demo",
    type: "components:example",
    registryDependencies: ["erc20-select-and-amount"],
    files: ["example/erc20-select-and-amount-demo.tsx"],
  },
  {
    name: "erc20-select-demo",
    type: "components:example",
    registryDependencies: ["erc20-select"],
    files: ["example/erc20-select-demo.tsx"],
  },
  {
    name: "erc20-symbol-demo",
    type: "components:example",
    registryDependencies: ["erc20-symbol"],
    files: ["example/erc20-symbol-demo.tsx"],
  },
  {
    name: "erc20-total-supply-demo",
    type: "components:example",
    registryDependencies: ["erc20-total-supply"],
    files: ["example/erc20-total-supply-demo.tsx"],
  },
  {
    name: "erc721-name-demo",
    type: "components:example",
    registryDependencies: ["erc721-name"],
    files: ["example/erc721-name-demo.tsx"],
  },
  {
    name: "erc721-symbol-demo",
    type: "components:example",
    registryDependencies: ["erc721-symbol"],
    files: ["example/erc721-symbol-demo.tsx"],
  },
  {
    name: "erc721-owner-of-demo",
    type: "components:example",
    registryDependencies: ["erc721-owner-of"],
    files: ["example/erc721-owner-of-demo.tsx"],
  },
  {
    name: "erc721-total-supply-demo",
    type: "components:example",
    registryDependencies: ["erc721-total-supply"],
    files: ["example/erc721-total-supply-demo.tsx"],
  },
  {
    name: "erc721-token-uri-demo",
    type: "components:example",
    registryDependencies: ["erc721-total-token-uri"],
    files: ["example/erc721-total-token-uri-demo.tsx"],
  },
  {
    name: "erc721-metadata-demo",
    type: "components:example",
    registryDependencies: ["erc721-metadata"],
    files: ["example/erc721-metadata-demo.tsx"],
  },
  {
    name: "error-message-demo",
    type: "components:example",
    registryDependencies: ["error-message"],
    files: ["example/error-message-demo.tsx"],
  },
  {
    name: "card-with-form",
    type: "components:example",
    registryDependencies: ["button", "card", "input", "label", "select"],
    files: ["example/card-with-form.tsx"],
  },
  {
    name: "network-selection-demo",
    type: "components:example",
    registryDependencies: ["button", "network-selection"],
    files: ["example/network-selection-demo.tsx"],
  },
]

export const registry: Registry = [...buidl, ...ui, ...example]
