import { Registry } from "@/registry/schema"

const buidl: Registry = [
  {
    name: "account-address",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-address.tsx"],
  },
  {
    name: "account-balance",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-balance.tsx"],
  },
  {
    name: "account-blockie",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-blockie.tsx"],
  },
  {
    name: "account-ens-avatar",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-ens-avatar.tsx"],
  },
  {
    name: "account-ens-name",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-ens-name.tsx"],
  },
  {
    name: "account-nonce",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/account-nonce.tsx"],
  },
  {
    name: "address",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/address.tsx"],
  },
  {
    name: "block-explorer-link",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/block-explorer-link.tsx"],
  },
  {
    name: "transaction-status",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/transaction-status.tsx"],
  },
  {
    name: "blockie",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/blockie.tsx"],
  },
  {
    name: "ens-avatar",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/ens-avatar.tsx"],
  },
  {
    name: "ens-name",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/ens-name.tsx"],
  },
  {
    name: "image-ipfs",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/image-ipfs.tsx"],
  },
  {
    name: "is-wallet-connected",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/is-wallet-connected.tsx"],
  },
  {
    name: "is-wallet-disconnected",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/is-wallet-disconnected.tsx"],
  },
  {
    name: "network-manage",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/network-manage.tsx"],
  },
  {
    name: "wallet-connect",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/wallet-connect.tsx"],
  },
  {
    name: "wallet-disconnect",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/wallet-disconnect.tsx"],
  },
  {
    name: "wallet-manage",
    type: "components:buidl",
    dependencies: ["wagmi"],
    files: ["buidl/wallet-manage.tsx"],
  },
  {
    name: "erc20-balance",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-balance.tsx"],
  },
  {
    name: "erc20-image",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-image.tsx"],
  },
  {
    name: "erc20-name",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-name.tsx"],
  },
  {
    name: "erc20-select-and-amount",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-select-and-amount.tsx"],
  },
  {
    name: "erc20-select",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-select.tsx"],
  },
  {
    name: "erc20-symbol",
    type: "components:buidl",
    folder: "erc20",
    dependencies: ["wagmi"],
    files: ["buidl/erc20/erc20-symbol.tsx"],
  },
]

const example: Registry = [
  {
    name: "account-address-demo",
    type: "components:example",
    registryDependencies: ["account-address"],
    files: ["example/account-address-demo.tsx"],
  },
  {
    name: "account-balance-demo",
    type: "components:example",
    registryDependencies: ["account-balance"],
    files: ["example/account-balance-demo.tsx"],
  },
  {
    name: "account-blockie-demo",
    type: "components:example",
    registryDependencies: ["account-blockie"],
    files: ["example/account-blockie-demo.tsx"],
  },
  {
    name: "account-ens-avatar-demo",
    type: "components:example",
    registryDependencies: ["account-ens-avatar"],
    files: ["example/account-ens-avatar-demo.tsx"],
  },
  {
    name: "account-ens-name-demo",
    type: "components:example",
    registryDependencies: ["account-ens-name"],
    files: ["example/account-ens-name-demo.tsx"],
  },
  {
    name: "account-nonce-demo",
    type: "components:example",
    registryDependencies: ["account-nonce"],
    files: ["example/account-nonce-demo.tsx"],
  },
  {
    name: "address-demo",
    type: "components:example",
    registryDependencies: ["address"],
    files: ["example/address-demo.tsx"],
  },
  {
    name: "block-explorer-link-demo",
    type: "components:example",
    registryDependencies: ["block-explorer-link"],
    files: ["example/block-explorer-link-demo.tsx"],
  },
  {
    name: "transaction-status-demo",
    type: "components:example",
    registryDependencies: ["transaction-status"],
    files: ["example/transaction-status-demo.tsx"],
  },
  {
    name: "blockie-demo",
    type: "components:example",
    registryDependencies: ["blockie"],
    files: ["example/blockie-demo.tsx"],
  },
  {
    name: "ens-avatar-demo",
    type: "components:example",
    registryDependencies: ["ens-avatar"],
    files: ["example/ens-avatar-demo.tsx"],
  },
  {
    name: "ens-name-demo",
    type: "components:example",
    registryDependencies: ["ens-name"],
    files: ["example/ens-name-demo.tsx"],
  },
  {
    name: "image-ipfs-demo",
    type: "components:example",
    registryDependencies: ["image-ipfs"],
    files: ["example/image-ipfs-demo.tsx"],
  },
  {
    name: "is-wallet-connected-demo",
    type: "components:example",
    registryDependencies: ["is-wallet-connected"],
    files: ["example/is-wallet-connected-demo.tsx"],
  },
  {
    name: "is-wallet-disconnected-demo",
    type: "components:example",
    registryDependencies: ["is-wallet-disconnected"],
    files: ["example/is-wallet-disconnected-demo.tsx"],
  },
  {
    name: "network-manage-demo",
    type: "components:example",
    registryDependencies: ["network-manage"],
    files: ["example/network-manage-demo.tsx"],
  },
  {
    name: "wallet-connect-demo",
    type: "components:example",
    registryDependencies: ["wallet-connect"],
    files: ["example/wallet-connect-demo.tsx"],
  },
  {
    name: "wallet-disconnect-demo",
    type: "components:example",
    registryDependencies: ["wallet-disconnect"],
    files: ["example/wallet-disconnect-demo.tsx"],
  },
  {
    name: "wallet-manage-demo",
    type: "components:example",
    registryDependencies: ["wallet-manage"],
    files: ["example/wallet-manage-demo.tsx"],
  },
  {
    name: "erc20-balance-demo",
    type: "components:example",
    registryDependencies: ["erc20-balance"],
    files: ["example/erc20-balance-demo.tsx"],
  },
  {
    name: "erc20-image-demo",
    type: "components:example",
    registryDependencies: ["erc20-image"],
    files: ["example/erc20-image-demo.tsx"],
  },
  {
    name: "erc20-name-demo",
    type: "components:example",
    registryDependencies: ["erc20-name"],
    files: ["example/erc20-name-demo.tsx"],
  },
  {
    name: "erc20-select-and-amount-demo",
    type: "components:example",
    registryDependencies: ["erc20-select-and-amount"],
    files: ["example/erc20-select-and-amount-demo.tsx"],
  },
  {
    name: "erc20-select-demo",
    type: "components:example",
    registryDependencies: ["erc20-select"],
    files: ["example/erc20-select-demo.tsx"],
  },
  {
    name: "erc20-symbol-demo",
    type: "components:example",
    registryDependencies: ["erc20-symbol"],
    files: ["example/erc20-symbol-demo.tsx"],
  },
]

export const registry: Registry = [...buidl, ...example]
